### ISSUE TITLE
请问下视频源api是从哪里获取的

### ISSUE THREAD

**Issue by xluu233** [cleverbao/All-IN#2]
软件很好用，最近也在想用Qt写一个类似软件，但是在网上都没有找到虎牙斗鱼的直播相关api。
请教下这些数据是怎么获取的，有公开api还是爬虫解析的

**Comment by ba0gu0** [comment]
> 

网页端抓取的，挺麻烦的，可以进入设置里面，有每个平台抓取的源代码，nodejs版本的。
